apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: web