apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-flask-app
          image: local/hello-flask
          imagePullPolicy: Never
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
